# Generated by Django 3.2.13 on 2022-07-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('phone_number', models.IntegerField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=40)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
