# Generated by Django 3.2.13 on 2022-07-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='seondary_no',
            field=models.IntegerField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
