# Generated by Django 3.2.13 on 2022-07-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_seondary_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='seconday_em',
            field=models.EmailField(default='sadasda', max_length=40),
            preserve_default=False,
        ),
    ]
