# Generated by Django 3.2.13 on 2022-07-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_seconday_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.BigIntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='seondary_no',
            field=models.BigIntegerField(max_length=20),
        ),
    ]
