# Generated by Django 3.2.13 on 2022-07-24 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20220724_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='seondary_no',
            field=models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
