version: '3.8'

services:
  app:
    container_name: django-reservation-app
    build: .
    command: bash -c " python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8080:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    container_name: django-reservation-db
    image: postgres:13.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=reservation_app_db
      - POSTGRES_HOST_AUTH_METHOD="trust"
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
